# Generated by Django 6.0.6 on 2026-06-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
