# Generated by Django 6.0.6 on 2026-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_subject_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('weekly', 'Weekly Test'), ('monthly', 'Monthly Test'), ('midterm', 'Mid Term'), ('final', 'Final Exam')], max_length=20),
        ),
    ]
