# Generated by Django 6.0.6 on 2026-06-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('mathematics', 'Mathematics'), ('english', 'English'), ('ict', 'ICT'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('ti ti-atom', 'Atom (Physics)'), ('ti ti-flask', 'Flask (Chemistry)'), ('ti ti-dna', 'DNA (Biology)'), ('ti ti-math-function', 'Math'), ('ti ti-book', 'Book'), ('ti ti-device-laptop', 'Laptop (ICT)'), ('ti ti-language', 'Language'), ('ti ti-pencil', 'Pencil')], default='ti ti-book', max_length=60)),
                ('icon_bg_color', models.CharField(default='#E6F1FB', max_length=10)),
                ('icon_color', models.CharField(default='#0C447C', max_length=10)),
                ('level', models.CharField(choices=[('six', 'SSC'), ('seven', 'SEVEN'), ('eight', 'EIGHT'), ('nine', 'NINE'), ('ten', 'TEN')], default='six', max_length=20)),
                ('fee_per_month', models.PositiveIntegerField(blank=True, help_text='Monthly fee in BDT', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notice_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('urgent', 'Urgent')], default='info', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('label', models.CharField(help_text='e.g. HSC Pass Rate', max_length=100)),
                ('value', models.CharField(help_text='e.g. 98% or 340', max_length=20)),
                ('tag', models.CharField(help_text='e.g. 2024 Board', max_length=50)),
                ('tag_bg', models.CharField(default='#EAF3DE', max_length=10)),
                ('tag_color', models.CharField(default='#27500A', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(default='Karnafuli Science Academy', max_length=200)),
                ('tagline', models.CharField(default="Chittagong's Premier Science Coaching", max_length=300)),
                ('established_year', models.PositiveIntegerField(default=2009)),
                ('hero_heading', models.CharField(default='Build Your Future with', max_length=300)),
                ('hero_subtext', models.TextField(default='Expert coaching for SSC C students.')),
                ('enroll_btn_text', models.CharField(default='Enroll for 2025 Batch', max_length=100)),
                ('enroll_btn_url', models.CharField(default='#', max_length=200)),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, default='House #12, Road #3, Nasirabad\nChittagong — 4210, Bangladesh')),
                ('office_hours', models.CharField(default='Sat – Thu: 8:00 AM – 9:00 PM | Friday: Closed', max_length=200)),
                ('how_to_reach', models.TextField(blank=True, default='Accessible via CNG, bus route 3 & 7, and rickshaw from GEC Circle')),
                ('google_maps_url', models.URLField(blank=True, default='https://maps.google.com')),
                ('google_maps_embed_url', models.URLField(blank=True, help_text='Google Maps embed iframe src URL')),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('brochure_url', models.CharField(blank=True, default='#', max_length=200)),
                ('stat_students', models.CharField(default='3,000+', max_length=20)),
                ('stat_experience', models.CharField(default='15+', max_length=20)),
                ('stat_pass_rate', models.CharField(default='92%', max_length=20)),
                ('stat_teachers', models.CharField(default='25+', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, help_text='e.g. Senior Lecturer', max_length=100)),
                ('subject', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('mathematics', 'Mathematics'), ('english', 'English'), ('ict', 'ICT'), ('other', 'Other')], default='other', max_length=30)),
                ('qualification', models.CharField(help_text='e.g. M.Sc. in Physics', max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('short_bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('avatar_initials', models.CharField(blank=True, help_text='Auto-generated if blank', max_length=3)),
                ('avatar_bg', models.CharField(default='#E6F1FB', max_length=10)),
                ('avatar_color', models.CharField(default='#0C447C', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BatchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(help_text='e.g. SSC Morning Batch A', max_length=100)),
                ('days', models.CharField(choices=[('sat_thu', 'Sat – Thu'), ('sat_wed', 'Sat – Wed'), ('fri_sat', 'Fri – Sat'), ('daily', 'Daily')], default='sat_thu', max_length=20)),
                ('time_slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('seats_total', models.PositiveIntegerField(default=25)),
                ('seats_enrolled', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='home.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='home.teacher')),
            ],
            options={
                'ordering': ['time_slot', 'batch_name'],
            },
        ),
    ]
