# Generated by Django 6.0.6 on 2026-06-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchschedule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='result',
            name='is_active',
        ),
    ]
