# Generated by Django 6.0.6 on 2026-07-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_batchschedule_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='academy_name',
            field=models.CharField(default='Pakundia Coaching Center', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='Pakundia, Kishoreganj, Bangladesh'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Pakundia, Kishoreganj — Premier Coaching Center', max_length=300),
        ),
    ]
